# Generated by Django 4.2.5 on 2023-09-17 06:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PDF',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='../uploads/')),
                ('uploaded_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Similarity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdf_summary', models.TextField()),
                ('rec_summary', models.TextField()),
                ('pdf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feyn_api.pdf')),
            ],
        ),
        migrations.CreateModel(
            name='Recording',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('pdf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feyn_api.pdf')),
            ],
        ),
        migrations.CreateModel(
            name='PDFSelect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('pdf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feyn_api.pdf')),
            ],
        ),
    ]
