# Generated by Django 4.2.5 on 2023-09-17 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feyn_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pdf',
            name='file',
            field=models.FileField(upload_to='uploads/'),
        ),
    ]
