# Generated by Django 4.2.5 on 2023-09-16 00:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feyn_api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pdfseries',
            old_name='_id',
            new_name='session_id',
        ),
    ]
