# Generated by Django 4.2.5 on 2023-09-17 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feyn_api', '0002_alter_pdf_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdf',
            name='filename',
            field=models.CharField(default='/', max_length=100),
            preserve_default=False,
        ),
    ]
