# Generated by Django 4.2.5 on 2023-09-16 16:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('feyn_api', '0003_rename_pdfseries_pdf'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pdf',
            old_name='session_id',
            new_name='pdf_id',
        ),
        migrations.RemoveField(
            model_name='pdf',
            name='text',
        ),
        migrations.CreateModel(
            name='Similarity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdf_summary', models.TextField()),
                ('rec_summary', models.TextField()),
                ('pdf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feyn_api.pdf')),
            ],
        ),
        migrations.CreateModel(
            name='Recording',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('pdf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feyn_api.pdf')),
            ],
        ),
        migrations.CreateModel(
            name='PDFSelect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('pdf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feyn_api.pdf')),
            ],
        ),
    ]
