# Generated by Django 4.2.5 on 2023-09-16 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feyn_api', '0004_rename_session_id_pdf_pdf_id_remove_pdf_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdf',
            name='filepath',
            field=models.TextField(default='/'),
        ),
    ]
