# Generated by Django 4.2.5 on 2023-09-17 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feyn_api', '0006_remove_pdf_pdf_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pdf',
            name='filepath',
        ),
        migrations.AddField(
            model_name='pdf',
            name='file',
            field=models.FileField(default=0, upload_to=''),
            preserve_default=False,
        ),
    ]
