# Generated by Django 4.2.5 on 2023-09-17 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feyn_api', '0008_rename_file_pdf_pdf'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pdf',
            old_name='pdf',
            new_name='file',
        ),
        migrations.AddField(
            model_name='pdf',
            name='uploaded_on',
            field=models.DateTimeField(auto_now_add=True, default=0),
            preserve_default=False,
        ),
    ]
